apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: openkintai
      images:
        - alias: openkintai
          imageName: moreillon/openkintai
          commonUpdateSettings:
            updateStrategy: newest-build
