apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: postgresql
spec:
  instances: 1
  enablePDB: false
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-standard-trixie
  enableSuperuserAccess: true

  env:
    - name: TZ
      value: Asia/tokyo

  storage:
    storageClass: local-path-provisioner-ssd
    size: 5Gi

  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: "2"
      memory: 1Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: linode
