apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: postgresql
spec:
  storageClassName: local-path-provisioner-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: postgresql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
    spec:
      containers:
        - name: postgresql
          image: pgvector/pgvector:0.8.1-pg18
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          envFrom:
            - secretRef:
                name: env
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: postgresql
spec:
  ports:
    - port: 5432
      nodePort: 30432
  selector:
    app.kubernetes.io/name: postgresql
  type: NodePort
