apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: postgresql
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-standard-trixie
  enableSuperuserAccess: true

  storage:
    storageClass: local-path-provisioner-ssd
    size: 5Gi

  bootstrap:
    initdb:
      import:
        type: monolith
        databases:
          - authentik
          - grafana
          - n8n
          - nextcloud
        roles:
          - authentik
          - grafana
          - n8n
          - nextcloud
        source:
          externalCluster: postgresql-standalone

  externalClusters:
    - name: postgresql-standalone
      connectionParameters:
        host: postgresql.postgresql
        user: postgres
        dbname: postgres
        sslmode: disable
      password:
        name: env
        key: POSTGRES_PASSWORD

  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: "2"
      memory: 1Gi

  # plugins:
  #   - name: barman-cloud.cloudnative-pg.io
  #     isWALArchiver: true
  #     parameters:
  #       barmanObjectName: linode
