apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: postgresql
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30432
  selector:
    cnpg.io/cluster: postgresql
    role: primary
