apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: n8n
  template:
    metadata:
      labels:
        app.kubernetes.io/name: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:2.27.4
          resources:
            requests:
              memory: "256Mi"
              cpu: "25m"
            limits:
              memory: "1Gi"
              cpu: "1"
          envFrom:
            - secretRef:
                name: env
          env:
            - name: GENERIC_TIMEZONE
              value: Asia/Tokyo
            - name: N8N_EDITOR_BASE_URL
              value: https://n8n.secondhomelab.com
            - name: WEBHOOK_URL
              value: https://n8n.secondhomelab.com

            # DB
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: DB_POSTGRESDB_HOST
              value: postgresql.postgresql
            - name: DB_POSTGRESDB_PORT
              value: "5432"

            # SMTP
            - name: N8N_SMTP_HOST
              value: smtp.mailgun.org
            - name: N8N_SMTP_PORT
              value: "465"
            - name: N8N_SMTP_SSL
              value: "true"
            - name: N8N_SMTP_STARTTLS
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
spec:
  ports:
    - port: 5678
  selector:
    app.kubernetes.io/name: n8n
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n
  namespace: n8n
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: N8n
    gethomepage.dev/icon: n8n
    gethomepage.dev/group: WAN

spec:
  hostnames:
    - n8n.secondhomelab.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: n8n
          port: 5678
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
