apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: nextcloud
spec:
  storageClassName: local-path-provisioner-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
