apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html
  namespace: nextcloud
spec:
  storageClassName: local-path-provisioner-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
