apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster

  settings.yaml: ""
  services.yaml: ""

  widgets.yaml: |
    - greeting:
        text_size: 3xl
        text: Welcome to Second Home(lab)

  docker.yaml: ""
  bookmarks.yaml: ""
  custom.css: ""
  custom.js: ""
