apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster

  settings.yaml: ""
  services.yaml: ""

  widgets.yaml: |
    - greeting:
        text_size: 4xl
        text: Welcome to Second Home(lab)

  docker.yaml: ""
  bookmarks.yaml: |
    - GitHub repositories:
      - secondhomelab-k8s:
          - icon: github
            href: https://github.com/maximemoreillon/secondhomelab-k8s
      - secondhomelab-talos:
          - icon: github
            href: https://github.com/maximemoreillon/secondhomelab-talos

  custom.css: ""
  custom.js: ""
