apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true

  settings.yaml: ""
  services.yaml: |
    - Tailnet:
      - Proxmox:
          href: http://100.110.209.113:8006
          icon: proxmox
      - Argo-CD:
          href: http://100.108.113.103:30080
          icon: argo-cd

  widgets.yaml: |
    # - logo:
    #     icon: https://avatars.githubusercontent.com/u/290229801
    - greeting:
        text_size: 2xl
        text: Welcome to Second Home(lab)
    # - kubernetes: # Neets metrics server
    #     cluster:
    #       show: true
    #       cpu: true
    #       memory: true
    #     nodes:
    #       show: false

  docker.yaml: ""
  bookmarks.yaml: |
    - Links:
      - github.com/secondhomelab:
          - icon: github
            href: https://github.com/secondhomelab
            description: Second Homelab GitHub Organization

  custom.css: ""
  custom.js: ""
