configs:
  params:
    server.insecure: true

server:
  service:
    type: NodePort

  # Tailnet only, through Envoy's tailnet listener
  httproute:
    enabled: true
    hostnames:
      - argocd.talos.tailnet.secondhomelab.com
    parentRefs:
      - name: eg
        namespace: envoy-gateway-system
        sectionName: tailnet
