apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |

    global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 30s

    scrape_configs:

      - job_name: node-exporter
        honor_timestamps: true
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets: 
              - node-exporter:9100
            labels:
              instance: node-exporter

      - job_name: apcupsd-exporter
        honor_timestamps: true
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets: 
              - apcupsd-exporter:9162
            labels: 
              instance: UPS

      # - job_name: cadvisor
      #   metrics_path: /metrics/cadvisor
      #   scheme: https
      #   tls_config:
      #     insecure_skip_verify: true
      #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #   kubernetes_sd_configs:
      #     - role: node
      #   relabel_configs:
      #     - action: labelmap
      #       regex: __meta_kubernetes_node_label_(.+)
      #     - target_label: __address__
      #       replacement: kubernetes.default.svc:443
      #     - source_labels: [__meta_kubernetes_node_name]
      #       regex: (.+)
      #       target_label: __metrics_path__
      #       replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

      - job_name: snmp-exporter
        metrics_path: /snmp
        scheme: http
        params:
          module: [if_mib]
          auth: [aruba_v3]
        static_configs:
          - targets:
              - 192.168.1.14 # Virtual Controller IP
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: snmp-exporter:9116
