apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.20.2
      helm:
        valueFiles:
          - $values/cert-manager/values.yml
    - repoURL: https://github.com/secondhomelab/k8s.git
      targetRevision: HEAD
      ref: values
      path: cert-manager
