apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord2line
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/secondhomelab/k8s.git
    path: discord2line
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: moreillon
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true
