apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  sources:
    - repoURL: docker.io/envoyproxy
      chart: gateway-helm
      targetRevision: v1.8.1
      # helm:
      #   valueFiles:
      #     - $values/envoy/values.yml
    - repoURL: https://github.com/secondhomelab/k8s.git
      targetRevision: HEAD
      path: envoy-gateway
      # ref: values
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
